### ISSUE TITLE
Loading files not working well

### ISSUE THREAD

**Issue by corranwebster** [force-h2020/force-wfmanager#129]
Often when loading (usually after a change to a plugin's code) the KPIs do not appear and it becomes impossible to add new ones to the workflow.

There are also occasions when loading a file seems to merge it with an existing workflow.

The logic of the file loader needs to be looked at.

**Comment by stefanoborini** [comment]
This was due to an old issue that has been fixed and was due to the fact that if an error occurred while loading a plugin, it would suspend execution. Now we intercept the error and therefore it has been fixed and will not produce a partial load anymore. It will instead stop loading and stay the way it was.
